source 'https://github.com/CocoaPods/Specs.git'

target 'Facebook-PromiseKit', :exclusive => true do
  pod "Facebook-PromiseKit", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "Facebook-PromiseKit", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
